### ISSUE TITLE
Change in venue

### ISSUE THREAD

**Issue by newb-dev-1008** [FACE-Amrita-Bengaluru/SLAC-2020#6] opened 2020-10-06 17:01 UTC
Add "Online" to the venue, i.e. make it:
"Amrita School of Engineering, Bangalore - Virtual Hack" or "Online Hack". Anything else that conveys the info and looks better is welcome.

**Comment by rohitraju1966** [comment] 2020-10-08 13:27
I'll do this one

**Comment by newb-dev-1008** [comment] 2020-10-08 13:30
@rohitraju1966 cool, you've been assigned. Send PR once done.

**Comment by rohitraju1966** [comment] 2020-10-09 10:42
hey! the changes i have made to the venue has already been merged so the issue is resolved right?

**Comment by aravindvnair99** [comment] 2020-10-09 11:02
@rohitraju1966 Right hadn't noticed a separate issue. Next time tag it.

Fixed in eb4c82c374b9c140847b3db9032bd37f7d2f3a3b

**Closed as completed by aravindvnair99** 2020-10-09 11:02 UTC
Labels: High Priority
